#!/usr/bin/env python3
"""Generate the playfield maze and background gradient tables for roms/demo.asm."""

# Left half of the playfield (20 columns); the right half is mirrored by CTRLPF.
# Top row first. Each row is 8 scanlines tall.
MAZE = [
    "XXXXXXXXXXXXXXXXXXXX",
    "X...................",
    "X...................",
    "X...................",
    "X....XXXX.......XX..",
    "X....X..........XX..",
    "X....X..............",
    "X...................",
    "X...................",
    "XXX.........XXXX....",
    "X...........X.......",
    "X...........X.......",
    "X...................",
    "X.....XXX...........",
    "X...................",
    "X...................",
    "X...............XXXX",
    "X...XX..............",
    "X...XX.....X........",
    "X..........X........",
    "X...................",
    "X...................",
    "X...................",
    "XXXXXXXXXXXXXXXXXXXX",
]

def pf_bytes(row):
    b = [1 if c == "X" else 0 for c in row]
    pf0 = sum(b[i] << (4 + i) for i in range(4))
    pf1 = sum(b[4 + i] << (7 - i) for i in range(8))
    pf2 = sum(b[12 + i] << i for i in range(8))
    return pf0, pf1, pf2

# The kernel indexes rows bottom-up (index 0 = bottom row).
rows = [pf_bytes(r) for r in reversed(MAZE)]

def table(name, values):
    out = [f"{name}"]
    for i in range(0, len(values), 8):
        out.append("        .byte " + ",".join(f"${v:02X}" for v in values[i:i + 8]))
    return "\n".join(out)

# 96 line-pairs, index 95 = top of screen: dusk sky fading into a dark floor.
bk = []
for y in range(96):
    t = 95 - y  # 0 at top
    if t < 32:
        bk.append(0x90 + (t // 8) * 2)     # blues
    elif t < 64:
        bk.append(0x80 + ((63 - t) // 8) * 2)
    else:
        bk.append(0xC0 + ((t - 64) // 11) * 2)  # greens


print("; generated by tools/gen-demo-tables.py")
print(table("PF0Tab", [r[0] for r in rows]))
print(table("PF1Tab", [r[1] for r in rows]))
print(table("PF2Tab", [r[2] for r in rows]))
print(table("BkTab", bk))
